name: Workflow con Triggers

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub Actions.
    inputs:
      nombre:
        description: "Nombre del usuario"
        required: true
        default: "Fede"
      lenguaje_favorito:
        description: "Lenguaje favorito del usuario"
        required: true
        default: "JavaScript"

jobs:
  configurar-entorno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm ci

      - name: Crear archivo .env
        run: echo "NOMBRE=${{ github.actor }}" > .env

      - name: Definir variables de entorno
        run: |
          echo "USERNAME=${{ github.event.inputs.nombre }}" >> $GITHUB_ENV
          echo "LANGUAGE=${{ github.event.inputs.lenguaje_favorito }}" >> $GITHUB_ENV

      - name: Correr script
        run: node main.js

  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm ci

      - name: Crear archivo .env
        run: echo "NOMBRE=${{ github.actor }}" > .env

      - name: Ejecutar main.js
        run: node main.js